---
version: '3.5'
services:

  nginx_proxy:
    image: reiz/nginx_proxy:0.0.3
    hostname: nginx_proxy
    container_name: nginx_proxy
    ports:
      - "8888:8888"
    volumes:
      - ../../connect/connect-aws-kinesis-source/repro-proxy/nginx_whitelist.conf:/usr/local/nginx/conf/nginx.conf

  connect:
    volumes:
        - $HOME/.aws/credentials:/root/.aws/credentials:ro
        - ../../connect/connect-aws-kinesis-source/kafka-connect-kinesis-1.3.4.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-kinesis/lib/kafka-connect-kinesis-1.3.4.jar:ro
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-kinesis
    dns: 0.0.0.0
